# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor

t1 = torch.rand(2, 3)
t1

tensor([[0.7249, 0.5688, 0.5253],
        [0.3290, 0.4454, 0.1787]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
t2 = torch.rand(3, 2)

# Perform matrix multiplication 

tt = torch.mm(t1, t2)   
tt


tensor([[0.6788, 1.1472],
        [0.6453, 1.1152]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(42)


# Create two random tensors
t1 = torch.rand(2, 3)   
t2 = torch.rand(3, 2)   


# Matrix multiply tensors
tt = torch.mm(t1, t2)
tt


tensor([[1.4450, 1.0493],
        [1.1750, 1.1700]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(42)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.cuda.manual_seed(42)

# Check for access to GPU
torch.cuda.is_available()   

# Create two random tensors on GPU
gt1 = torch.rand(2, 3).cuda()
gt2 = torch.rand(3, 2).cuda()



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
m = gt1 @ gt2
m

tensor([[0.6049, 1.4124],
        [0.5236, 1.1375]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
m.max()

# Find min
m.min()


tensor(0.5236, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [13]:
# Find arg max
m.argmax()


# Find arg min
m.argmin()


tensor(2, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
# Set seed
torch.manual_seed(7)


# Create random tensor
t = torch.rand(1,1,1,10)
t


# Remove single dimensions
t.squeeze()


# Print out tensors and their shapes
print(t)
print(t.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
